"""初始城市 / 区域 / 景点数据。

坐标一律按 **WGS-84** 书写（这是公开资料和 GPS 的通用坐标系），入库时由
`geo.to_gcj02` 统一转成 GCJ-02，以便和主项目的高德底图对齐。

这些坐标是人工整理的近似值，精度够做人流密度分区展示，但不是测绘级数据。
需要修正时直接改这里，然后 `python run.py --reseed` 重建。
"""

from __future__ import annotations

# city_id, 名称, 英文名, 中心点 [lng, lat], 默认缩放, 可选 bounds [minLng,minLat,maxLng,maxLat]
CITIES: list[dict] = [
    {
        "city_id": "macau",
        "name": "澳门",
        "name_en": "Macau",
        "center": [113.5439, 22.1830],
        "default_zoom": 13,
        "bounds": [113.5200, 22.1050, 113.5980, 22.2200],
    },
    {
        "city_id": "hongkong",
        "name": "香港",
        "name_en": "Hong Kong",
        "center": [114.1694, 22.3193],
        "default_zoom": 11,
        "bounds": [113.8300, 22.1500, 114.4400, 22.5600],
    },
    {
        "city_id": "guangzhou",
        "name": "广州",
        "name_en": "Guangzhou",
        "center": [113.2644, 23.1291],
        "default_zoom": 11,
        "bounds": [113.1000, 22.9500, 113.5000, 23.3000],
    },
    {
        "city_id": "shenzhen",
        "name": "深圳",
        "name_en": "Shenzhen",
        "center": [114.0579, 22.5431],
        "default_zoom": 11,
        "bounds": [113.7500, 22.4200, 114.3500, 22.7000],
    },
]

REGIONS: list[dict] = [
    # ── 澳门：堂区 / 填海区 ────────────────────────────────────────────────
    {
        "region_id": "macau-d-fatima",
        "city_id": "macau",
        "level": "district",
        "name": "花地玛堂区",
        "name_en": "Nossa Senhora de Fátima",
        "aliases": ["北区", "黑沙环"],
        "center": [113.5510, 22.2130],
    },
    {
        "region_id": "macau-d-santo-antonio",
        "city_id": "macau",
        "level": "district",
        "name": "圣安多尼堂区",
        "name_en": "Santo António",
        "aliases": ["花王堂区", "大三巴区"],
        "center": [113.5390, 22.1980],
    },
    {
        "region_id": "macau-d-sao-lazaro",
        "city_id": "macau",
        "level": "district",
        "name": "望德堂区",
        "name_en": "São Lázaro",
        "aliases": ["疯堂区"],
        "center": [113.5490, 22.1960],
    },
    {
        "region_id": "macau-d-se",
        "city_id": "macau",
        "level": "district",
        "name": "大堂区",
        "name_en": "Sé",
        "aliases": ["主教座堂区"],
        "center": [113.5460, 22.1900],
    },
    {
        "region_id": "macau-d-sao-lourenco",
        "city_id": "macau",
        "level": "district",
        "name": "风顺堂区",
        "name_en": "São Lourenço",
        "aliases": ["圣老楞佐堂区"],
        "center": [113.5360, 22.1870],
    },
    {
        "region_id": "macau-d-carmo",
        "city_id": "macau",
        "level": "district",
        "name": "嘉模堂区",
        "name_en": "Nossa Senhora do Carmo",
        "aliases": ["氹仔", "凼仔"],
        "center": [113.5570, 22.1560],
    },
    {
        "region_id": "macau-d-cotai",
        "city_id": "macau",
        "level": "district",
        "name": "路氹填海区",
        "name_en": "Cotai",
        "aliases": ["路氹城", "金光大道"],
        "center": [113.5660, 22.1450],
    },
    {
        "region_id": "macau-d-sao-francisco",
        "city_id": "macau",
        "level": "district",
        "name": "圣方济各堂区",
        "name_en": "São Francisco Xavier",
        "aliases": ["路环"],
        "center": [113.5620, 22.1200],
    },
    # ── 澳门：街道 ────────────────────────────────────────────────────────
    {
        "region_id": "macau-s-almeida-ribeiro",
        "city_id": "macau",
        "parent_id": "macau-d-se",
        "level": "street",
        "name": "新马路",
        "name_en": "Avenida de Almeida Ribeiro",
        "aliases": ["亚美打利庇卢大马路"],
        "center": [113.5400, 22.1930],
    },
    {
        "region_id": "macau-s-sao-paulo",
        "city_id": "macau",
        "parent_id": "macau-d-santo-antonio",
        "level": "street",
        "name": "大三巴街",
        "name_en": "Rua de São Paulo",
        "center": [113.5405, 22.1968],
    },
    {
        "region_id": "macau-s-palha",
        "city_id": "macau",
        "parent_id": "macau-d-santo-antonio",
        "level": "street",
        "name": "卖草地街",
        "name_en": "Rua da Palha",
        "center": [113.5395, 22.1948],
    },
    {
        "region_id": "macau-s-felicidade",
        "city_id": "macau",
        "parent_id": "macau-d-se",
        "level": "street",
        "name": "福隆新街",
        "name_en": "Rua da Felicidade",
        "center": [113.5390, 22.1920],
    },
    {
        "region_id": "macau-s-cinco-outubro",
        "city_id": "macau",
        "parent_id": "macau-d-santo-antonio",
        "level": "street",
        "name": "十月初五日街",
        "name_en": "Rua de Cinco de Outubro",
        "center": [113.5375, 22.1955],
    },
    {
        "region_id": "macau-s-sao-domingos",
        "city_id": "macau",
        "parent_id": "macau-d-santo-antonio",
        "level": "street",
        "name": "板樟堂前地",
        "name_en": "Largo de São Domingos",
        "center": [113.5398, 22.1940],
    },
    {
        "region_id": "macau-s-horta-costa",
        "city_id": "macau",
        "parent_id": "macau-d-fatima",
        "level": "street",
        "name": "高士德大马路",
        "name_en": "Avenida de Horta e Costa",
        "center": [113.5480, 22.2030],
    },
    {
        "region_id": "macau-s-amizade",
        "city_id": "macau",
        "parent_id": "macau-d-se",
        "level": "street",
        "name": "友谊大马路",
        "name_en": "Avenida da Amizade",
        "center": [113.5520, 22.1930],
    },
    {
        "region_id": "macau-s-ferreira-almeida",
        "city_id": "macau",
        "parent_id": "macau-d-sao-lazaro",
        "level": "street",
        "name": "荷兰园大马路",
        "name_en": "Avenida do Conselheiro Ferreira de Almeida",
        "center": [113.5475, 22.1975],
    },
    {
        "region_id": "macau-s-cunha",
        "city_id": "macau",
        "parent_id": "macau-d-carmo",
        "level": "street",
        "name": "官也街",
        "name_en": "Rua do Cunha",
        "aliases": ["氹仔手信街"],
        "center": [113.5563, 22.1565],
    },
    {
        "region_id": "macau-s-braganca",
        "city_id": "macau",
        "parent_id": "macau-d-carmo",
        "level": "street",
        "name": "地堡街",
        "name_en": "Rua de Bragança",
        "center": [113.5540, 22.1570],
    },
    {
        "region_id": "macau-s-coloane-vila",
        "city_id": "macau",
        "parent_id": "macau-d-sao-francisco",
        "level": "street",
        "name": "路环市区",
        "name_en": "Coloane Village",
        "aliases": ["路环旧市区"],
        "center": [113.5645, 22.1180],
    },
    # ── 澳门：景点 ────────────────────────────────────────────────────────
    {
        "region_id": "macau-poi-ruins-st-paul",
        "city_id": "macau",
        "parent_id": "macau-s-sao-paulo",
        "level": "poi",
        "name": "大三巴牌坊",
        "name_en": "Ruins of St. Paul's",
        "aliases": ["大三巴", "圣保禄大教堂遗址"],
        "center": [113.5406, 22.1976],
        "radius_m": 120,
    },
    {
        "region_id": "macau-poi-senado-square",
        "city_id": "macau",
        "parent_id": "macau-s-almeida-ribeiro",
        "level": "poi",
        "name": "议事亭前地",
        "name_en": "Senado Square",
        "aliases": ["喷水池", "议事亭"],
        "center": [113.5397, 22.1936],
        "radius_m": 110,
    },
    {
        "region_id": "macau-poi-mount-fortress",
        "city_id": "macau",
        "parent_id": "macau-d-santo-antonio",
        "level": "poi",
        "name": "大炮台",
        "name_en": "Mount Fortress",
        "center": [113.5418, 22.1971],
        "radius_m": 100,
    },
    {
        "region_id": "macau-poi-macao-museum",
        "city_id": "macau",
        "parent_id": "macau-d-santo-antonio",
        "level": "poi",
        "name": "澳门博物馆",
        "name_en": "Macao Museum",
        "center": [113.5415, 22.1968],
        "radius_m": 80,
    },
    {
        "region_id": "macau-poi-st-dominic",
        "city_id": "macau",
        "parent_id": "macau-s-sao-domingos",
        "level": "poi",
        "name": "玫瑰堂",
        "name_en": "St. Dominic's Church",
        "aliases": ["板樟堂"],
        "center": [113.5399, 22.1943],
        "radius_m": 60,
    },
    {
        "region_id": "macau-poi-leal-senado",
        "city_id": "macau",
        "parent_id": "macau-s-almeida-ribeiro",
        "level": "poi",
        "name": "市政署大楼",
        "name_en": "Leal Senado Building",
        "aliases": ["民政总署大楼"],
        "center": [113.5392, 22.1930],
        "radius_m": 60,
    },
    {
        "region_id": "macau-poi-a-ma-temple",
        "city_id": "macau",
        "parent_id": "macau-d-sao-lourenco",
        "level": "poi",
        "name": "妈阁庙",
        "name_en": "A-Ma Temple",
        "center": [113.5312, 22.1863],
        "radius_m": 90,
    },
    {
        "region_id": "macau-poi-macau-tower",
        "city_id": "macau",
        "parent_id": "macau-d-sao-lourenco",
        "level": "poi",
        "name": "澳门旅游塔",
        "name_en": "Macau Tower",
        "center": [113.5367, 22.1799],
        "radius_m": 150,
    },
    {
        "region_id": "macau-poi-guia-fortress",
        "city_id": "macau",
        "parent_id": "macau-d-sao-lazaro",
        "level": "poi",
        "name": "东望洋灯塔",
        "name_en": "Guia Fortress and Lighthouse",
        "aliases": ["松山灯塔"],
        "center": [113.5495, 22.1965],
        "radius_m": 130,
    },
    {
        "region_id": "macau-poi-lou-lim-ioc",
        "city_id": "macau",
        "parent_id": "macau-d-sao-lazaro",
        "level": "poi",
        "name": "卢廉若公园",
        "name_en": "Lou Lim Ioc Garden",
        "center": [113.5476, 22.1993],
        "radius_m": 110,
    },
    {
        "region_id": "macau-poi-fishermans-wharf",
        "city_id": "macau",
        "parent_id": "macau-s-amizade",
        "level": "poi",
        "name": "渔人码头",
        "name_en": "Macau Fisherman's Wharf",
        "center": [113.5556, 22.1946],
        "radius_m": 200,
    },
    {
        "region_id": "macau-poi-grand-lisboa",
        "city_id": "macau",
        "parent_id": "macau-d-se",
        "level": "poi",
        "name": "新葡京",
        "name_en": "Grand Lisboa",
        "center": [113.5433, 22.1892],
        "radius_m": 120,
    },
    {
        "region_id": "macau-poi-science-center",
        "city_id": "macau",
        "parent_id": "macau-d-se",
        "level": "poi",
        "name": "澳门科学馆",
        "name_en": "Macao Science Center",
        "center": [113.5507, 22.1893],
        "radius_m": 120,
    },
    {
        "region_id": "macau-poi-taipa-houses",
        "city_id": "macau",
        "parent_id": "macau-d-carmo",
        "level": "poi",
        "name": "龙环葡韵",
        "name_en": "Taipa Houses Museum",
        "center": [113.5599, 22.1548],
        "radius_m": 130,
    },
    {
        "region_id": "macau-poi-carmel-church",
        "city_id": "macau",
        "parent_id": "macau-d-carmo",
        "level": "poi",
        "name": "嘉模圣母堂",
        "name_en": "Our Lady of Carmel Church",
        "center": [113.5590, 22.1552],
        "radius_m": 70,
    },
    {
        "region_id": "macau-poi-venetian",
        "city_id": "macau",
        "parent_id": "macau-d-cotai",
        "level": "poi",
        "name": "威尼斯人",
        "name_en": "The Venetian Macao",
        "center": [113.5595, 22.1459],
        "radius_m": 250,
    },
    {
        "region_id": "macau-poi-parisian",
        "city_id": "macau",
        "parent_id": "macau-d-cotai",
        "level": "poi",
        "name": "巴黎人",
        "name_en": "The Parisian Macao",
        "center": [113.5645, 22.1425],
        "radius_m": 200,
    },
    {
        "region_id": "macau-poi-londoner",
        "city_id": "macau",
        "parent_id": "macau-d-cotai",
        "level": "poi",
        "name": "伦敦人",
        "name_en": "The Londoner Macao",
        "center": [113.5620, 22.1450],
        "radius_m": 200,
    },
    {
        "region_id": "macau-poi-galaxy",
        "city_id": "macau",
        "parent_id": "macau-d-cotai",
        "level": "poi",
        "name": "银河综合渡假城",
        "name_en": "Galaxy Macau",
        "center": [113.5555, 22.1490],
        "radius_m": 220,
    },
    {
        "region_id": "macau-poi-hac-sa",
        "city_id": "macau",
        "parent_id": "macau-d-sao-francisco",
        "level": "poi",
        "name": "黑沙海滩",
        "name_en": "Hac Sa Beach",
        "center": [113.5620, 22.1148],
        "radius_m": 300,
    },
    {
        "region_id": "macau-poi-cheoc-van",
        "city_id": "macau",
        "parent_id": "macau-d-sao-francisco",
        "level": "poi",
        "name": "竹湾海滩",
        "name_en": "Cheoc Van Beach",
        "center": [113.5555, 22.1150],
        "radius_m": 200,
    },
    {
        "region_id": "macau-poi-st-francis-chapel",
        "city_id": "macau",
        "parent_id": "macau-s-coloane-vila",
        "level": "poi",
        "name": "圣方济各圣堂",
        "name_en": "Chapel of St. Francis Xavier",
        "center": [113.5645, 22.1178],
        "radius_m": 70,
    },
    {
        "region_id": "macau-poi-lord-stows",
        "city_id": "macau",
        "parent_id": "macau-s-coloane-vila",
        "level": "poi",
        "name": "安德鲁饼店",
        "name_en": "Lord Stow's Bakery",
        "aliases": ["葡挞"],
        "center": [113.5648, 22.1175],
        "radius_m": 40,
    },
    {
        "region_id": "macau-poi-university",
        "city_id": "macau",
        "parent_id": "macau-d-cotai",
        "level": "poi",
        "name": "澳门大学",
        "name_en": "University of Macau",
        "center": [113.5450, 22.1300],
        "radius_m": 400,
    },
    # ── 香港 ─────────────────────────────────────────────────────────────
    {
        "region_id": "hk-d-central-western",
        "city_id": "hongkong",
        "level": "district",
        "name": "中西区",
        "name_en": "Central and Western",
        "center": [114.1547, 22.2855],
    },
    {
        "region_id": "hk-d-wan-chai",
        "city_id": "hongkong",
        "level": "district",
        "name": "湾仔区",
        "name_en": "Wan Chai",
        "center": [114.1826, 22.2783],
    },
    {
        "region_id": "hk-d-yau-tsim-mong",
        "city_id": "hongkong",
        "level": "district",
        "name": "油尖旺区",
        "name_en": "Yau Tsim Mong",
        "center": [114.1722, 22.3130],
    },
    {
        "region_id": "hk-d-islands",
        "city_id": "hongkong",
        "level": "district",
        "name": "离岛区",
        "name_en": "Islands",
        "center": [113.9450, 22.2600],
    },
    {
        "region_id": "hk-poi-victoria-peak",
        "city_id": "hongkong",
        "parent_id": "hk-d-central-western",
        "level": "poi",
        "name": "太平山顶",
        "name_en": "Victoria Peak",
        "aliases": ["山顶缆车"],
        "center": [114.1494, 22.2759],
        "radius_m": 250,
    },
    {
        "region_id": "hk-poi-avenue-of-stars",
        "city_id": "hongkong",
        "parent_id": "hk-d-yau-tsim-mong",
        "level": "poi",
        "name": "星光大道",
        "name_en": "Avenue of Stars",
        "center": [114.1729, 22.2934],
        "radius_m": 200,
    },
    {
        "region_id": "hk-poi-times-square",
        "city_id": "hongkong",
        "parent_id": "hk-d-wan-chai",
        "level": "poi",
        "name": "铜锣湾时代广场",
        "name_en": "Times Square",
        "center": [114.1820, 22.2783],
        "radius_m": 150,
    },
    {
        "region_id": "hk-poi-ladies-market",
        "city_id": "hongkong",
        "parent_id": "hk-d-yau-tsim-mong",
        "level": "poi",
        "name": "旺角女人街",
        "name_en": "Ladies' Market",
        "center": [114.1700, 22.3195],
        "radius_m": 150,
    },
    {
        "region_id": "hk-poi-big-buddha",
        "city_id": "hongkong",
        "parent_id": "hk-d-islands",
        "level": "poi",
        "name": "天坛大佛",
        "name_en": "Tian Tan Buddha",
        "aliases": ["昂坪"],
        "center": [113.9050, 22.2540],
        "radius_m": 300,
    },
    {
        "region_id": "hk-poi-disneyland",
        "city_id": "hongkong",
        "parent_id": "hk-d-islands",
        "level": "poi",
        "name": "香港迪士尼乐园",
        "name_en": "Hong Kong Disneyland",
        "center": [114.0432, 22.3130],
        "radius_m": 500,
    },
    # ── 广州 ─────────────────────────────────────────────────────────────
    {
        "region_id": "gz-d-yuexiu",
        "city_id": "guangzhou",
        "level": "district",
        "name": "越秀区",
        "name_en": "Yuexiu",
        "center": [113.2664, 23.1288],
    },
    {
        "region_id": "gz-d-tianhe",
        "city_id": "guangzhou",
        "level": "district",
        "name": "天河区",
        "name_en": "Tianhe",
        "center": [113.3610, 23.1247],
    },
    {
        "region_id": "gz-d-liwan",
        "city_id": "guangzhou",
        "level": "district",
        "name": "荔湾区",
        "name_en": "Liwan",
        "center": [113.2440, 23.1260],
    },
    {
        "region_id": "gz-poi-canton-tower",
        "city_id": "guangzhou",
        "parent_id": "gz-d-tianhe",
        "level": "poi",
        "name": "广州塔",
        "name_en": "Canton Tower",
        "aliases": ["小蛮腰"],
        "center": [113.3245, 23.1066],
        "radius_m": 200,
    },
    {
        "region_id": "gz-poi-shamian",
        "city_id": "guangzhou",
        "parent_id": "gz-d-liwan",
        "level": "poi",
        "name": "沙面岛",
        "name_en": "Shamian Island",
        "center": [113.2420, 23.1078],
        "radius_m": 350,
    },
    {
        "region_id": "gz-poi-chen-clan",
        "city_id": "guangzhou",
        "parent_id": "gz-d-liwan",
        "level": "poi",
        "name": "陈家祠",
        "name_en": "Chen Clan Ancestral Hall",
        "center": [113.2440, 23.1290],
        "radius_m": 120,
    },
    {
        "region_id": "gz-poi-beijing-road",
        "city_id": "guangzhou",
        "parent_id": "gz-d-yuexiu",
        "level": "poi",
        "name": "北京路步行街",
        "name_en": "Beijing Road Pedestrian Street",
        "center": [113.2670, 23.1230],
        "radius_m": 250,
    },
    {
        "region_id": "gz-poi-baiyun-mountain",
        "city_id": "guangzhou",
        "parent_id": "gz-d-yuexiu",
        "level": "poi",
        "name": "白云山",
        "name_en": "Baiyun Mountain",
        "center": [113.2960, 23.1830],
        "radius_m": 600,
    },
    # ── 深圳 ─────────────────────────────────────────────────────────────
    {
        "region_id": "sz-d-futian",
        "city_id": "shenzhen",
        "level": "district",
        "name": "福田区",
        "name_en": "Futian",
        "center": [114.0550, 22.5220],
    },
    {
        "region_id": "sz-d-nanshan",
        "city_id": "shenzhen",
        "level": "district",
        "name": "南山区",
        "name_en": "Nanshan",
        "center": [113.9300, 22.5330],
    },
    {
        "region_id": "sz-d-luohu",
        "city_id": "shenzhen",
        "level": "district",
        "name": "罗湖区",
        "name_en": "Luohu",
        "center": [114.1230, 22.5480],
    },
    {
        "region_id": "sz-poi-window-of-the-world",
        "city_id": "shenzhen",
        "parent_id": "sz-d-nanshan",
        "level": "poi",
        "name": "世界之窗",
        "name_en": "Window of the World",
        "center": [113.9740, 22.5390],
        "radius_m": 400,
    },
    {
        "region_id": "sz-poi-happy-valley",
        "city_id": "shenzhen",
        "parent_id": "sz-d-nanshan",
        "level": "poi",
        "name": "欢乐谷",
        "name_en": "Happy Valley",
        "center": [113.9800, 22.5390],
        "radius_m": 400,
    },
    {
        "region_id": "sz-poi-shenzhen-bay-park",
        "city_id": "shenzhen",
        "parent_id": "sz-d-nanshan",
        "level": "poi",
        "name": "深圳湾公园",
        "name_en": "Shenzhen Bay Park",
        "center": [113.9420, 22.4840],
        "radius_m": 700,
    },
    {
        "region_id": "sz-poi-dongmen",
        "city_id": "shenzhen",
        "parent_id": "sz-d-luohu",
        "level": "poi",
        "name": "东门步行街",
        "name_en": "Dongmen Pedestrian Street",
        "center": [114.1200, 22.5470],
        "radius_m": 250,
    },
    {
        "region_id": "sz-poi-lianhuashan",
        "city_id": "shenzhen",
        "parent_id": "sz-d-futian",
        "level": "poi",
        "name": "莲花山公园",
        "name_en": "Lianhuashan Park",
        "center": [114.0570, 22.5560],
        "radius_m": 450,
    },
]
