idea.config.path=D:/Android_studio/LensGoCache/studio/config
idea.system.path=D:/Android_studio/LensGoCache/studio/system
idea.plugins.path=D:/Android_studio/LensGoCache/studio/plugins
idea.log.path=D:/Android_studio/LensGoCache/studio/log
